### ISSUE TITLE
[Suggestion] Sync clone respawning

### ISSUE THREAD

**Issue by xJon** [Midnight145/blightfall-issue-tracker#128]
Kind of a wild idea but I figured to put it out there. It might be possible to integrate Blightfall respawning "clones" with the [Sync mod](https://github.com/iChun/Sync/tree/b39ba210261e8e5d906f77d57ea6882ad040f502) (open source). Would most likely require quite a bit of work, but would also have an [amazing immersive effect](https://youtube.com/clip/UgkxM88xqQipYm64JW0QETN70no70mIb2OQK) on respawn (which could be on the Jaded).

**Comment by Midnight145** [comment]
I do like the idea, and I do think it's really cool, but I don't think it's worth the sacrifice of forcing respawns on the Jaded instead of having a spawnpoint at your base/wherever your bed is. It's a neat animation that'd be cool the first few times, but I think for most people it'd get old pretty quick.
