### ISSUE TITLE
Pam's Fish aren't OreDict'd

### ISSUE THREAD

**Issue by ZerVexon** [Midnight145/blightfall-issue-tracker#60]
The fish from Pam's Harvestcraft are not counted as Raw Fish via OreDictionary. This includes, at least, Carp, Catfish, and Snapper.

These are still obtainable via fishing, but are also hidden from NEI.

**Comment by Midnight145** [comment]
Fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/f8321f3dfe36a3677e08f08b8b50c4e12c9d3077). It looks like they were meant to be unobtainable in the first place, so I'm leaving them otherwise hidden, as I couldn't find a way to modify the fishing loot table with minetweaker.
