### ISSUE TITLE
New NEI tabs don't properly display certain icons

### ISSUE THREAD

**Issue by puncrafter** [Midnight145/blightfall-issue-tracker#7]
Some of the NEI tabs have blocks as their icons, but some don't. Those that don't usually have what I think is an error message underneath them. Attached is a screenshot.

![image](https://user-images.githubusercontent.com/53954921/216446284-db4cb011-91f7-4462-9ca9-aa5fc81fd40e.png)

**Comment by Midnight145** [comment]
This is due to "regular" NEI not supporting the tabs like that, so by default, most mods don't have support for the block icon instead of just the first two letters. To fix all of these would require custom builds of thermal, botania, neiplugins, etc. which I don't know if is worth it in my opinion.

**Comment by mitchej123** [comment]
The handler info can also be added to handlers.csv and PRd into nei.  


https://github.com/GTNewHorizons/NotEnoughItems/pull/339 for example

**Comment by Midnight145** [comment]
Thank you!

Latest NEI already has botania handlers--but they're for a newer version. I don't think I'm gonna PR, just because it is for an outdated version of Botania, but this will be fixed in the new build.

[Commit here](https://github.com/Midnight145/NotEnoughItems/commit/699bb01ff53fe1bbd4505b852ecbf13099e08ba4)
