### ISSUE TITLE
AE2 Autocrafting problems

### ISSUE THREAD

**Issue by Solarshade** [Midnight145/blightfall-issue-tracker#74]
AE2 auto-crafting seems to have issues in the most recent version, if you use the me interface in panel form, it has issues with making items as components of other items, specifically getting stuck unable to use those first items. However, if you use the block form, it will instead have the issue of stalling after a certain amount of time, meaning that any request for significantly more than a stack of items will fail to complete. I'm unsure if this is a bug with the modpack or just with this version of AE2 though. The bug only seems to show up when using processing recipies, being fine if you are using assemblers.

Edit: For an example of the first problem, an auto-crafting setup using ME interface's in panel form, with recipes for printed circuit components, and the processors themselves will stall if requested to craft processors from raw materials, as the system will create the printed circuits, but then simply not use them to create the processors.

**Comment by Midnight145** [comment]
Can you send me your setup?

**Comment by Solarshade** [comment]
Here is a test world I made to demonstrate the bug. It has 2 separate setups, both in Delta, connected to an ME system: 1 which turns cobblestone into sand into glass, and one that makes processors. To demonstrate stalling when components are not used, try to make any processor at an amount higher than the printed circuits of that type already in the system. Stalling over time is much less consistent, but I was able to achieve it by requesting the system make 1000 glass. It successfully made sand and then glass until it randomly stalled with 156 glass left to craft. You will need to cancel the two presently active crafting requests, as they are both stalled and will not proceed. [Link](https://drive.google.com/drive/folders/1oHhj5kljxH-d8JX5tWKiUyKQh4aduKCW?usp=drive_link)

**Comment by Midnight145** [comment]
You can try making an issue [here](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/issues), but it's more than likely an issue with ae2 rather than Blightfall itself

**Comment by dash16** [comment]
I thought I was going crazy, but I'm running into this bug myself.  For any crafting recipe where all ingredients are currently in the ME network, crafting completes.  For any recipe that has multiple steps, such as first craft quartz glass, then craft a blank pattern, it fails.  The blank pattern is stuck on scheduling, and will never complete.  If you cancel the craft, then submit the job again, it completes because the previous attempt made quartz glass and now all the necessary ingredients are available.

To be clear, prior to the CE release, AE2 auto crafting did not have these issues.  I've played through this pack twice, and came back after the CE release, and am hitting an absolute wall trying to get auto-crafting to work.  Thank you @Solarshade for pointing out the block form of the Interface is working (better, at least), I can use that as a workaround.  I guess I'll find out if sending large jobs causes those to fail in some way too.

**Comment by Solarshade** [comment]
@dash16 From what I remember the block form does still have issues unfortunately, with it seemingly stalling after a certain amount of time and also not knowing when to stop putting stuff in during that time. So it just keeps piling items into whatever container the interface is linked to for a short time, and then stops, leading to either a recipe stalling or overproducing.

**Comment by Midnight145** [comment]
this seems to be fixed in next patch, though it introduces a different bug with the crescent hammer that I'm working on getting resolved
