### ISSUE TITLE
Taffy has unbalanced aspect values.

### ISSUE THREAD

**Issue by Nikolay-Sitnikov** [Midnight145/blightfall-issue-tracker#85]
The food Taffy has Thaumcraft Aspects of 4 Metallum & 1 Aqua. This is most likely because Thaumcraft includes the worth of the Saucepan in every Taffy.

Using this exploit, I can turn 2 Sugar into 2 Nuggets of a metal.

**Comment by tiflu** [comment]
this is an issue for a lot of things. for example, a lot of other pams food, such as ice cream. additionally, things like inscribed materials (such as silicon) do the same. iirc inscribed silicon has 32 metallum. unsure if it's viable to be fixed, but it's certainly not specific to taffy

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/0fbb0080ec7fcf4855b3e9c48f9c8e703a49e65f)

Most pams foods have this problem, but frankly, I'm not interested in going over every pams food to fix it. It's easy enough to remove, if someone wants to go through and remove all of them and make a pull request, be my guest, but IMO it's not worth it.
