### ISSUE TITLE
"A New Dawn" The Dark One quest broken

### ISSUE THREAD

**Issue by ajohnstonTE** [Midnight145/blightfall-issue-tracker#86]
The Ritual Diviner, regardless of the tier present in your inventory, does not get detected for the quest and as a result the quest cannot be completed.
![image](https://github.com/Midnight145/blightfall-issue-tracker/assets/47606527/78ca6e05-8fb4-4e9c-9ace-96385a0b65aa)

**Comment by tiflu** [comment]
iirc there's two checks it has for nbt:
1. is it the right tier? in this case, the dawn tier. there's three total, it's the final one
2. iirc it has to have whatever the default ritual is selected. because nbt.
so I'd make sure you're using the dawn diviner, and then circle through every ritual and try to submit it
if that doesn't work, idk

**Comment by Midnight145** [comment]
i just need to change it from being strict nbt detection to just fuzzy, because with blood magic items when you right click with them they get bound to you which adds additional nbt data so there's no great way to check for it. I'll just add a note in there saying to build it, it requires the Dawn tier because there's no way for me to just check the tier.

Unsure if this'll make it in the next patch or not, but it will get done eventually

**Comment by Midnight145** [comment]
fixed in Midnight145/blightfall-issue-tracker@3ca3913d91a04f1d891796f7e49fe76685190d47
