### ISSUE TITLE
Misc fixes.

### ISSUE THREAD

**Issue by Midnight145** [Midnight145/blightfall-issue-tracker#89]
https://discord.com/channels/457095816771928076/787989049029427200/1189469643354685540

```
Chisel glass panes & iron bars (localized name issues):
#0688/1 through /9 (chisel:chisel.fenceIron)
#0689/1 through /4 and /12 through /15 (chisel:chisel.glassPane)

Compressed Dirt/Sand (description issues):
#0927/8 through /11 (ExtraUtilities:cobblestone_compressed)
#0927/14 and /15 (ExtraUtilities:cobblestone_compressed)

Warding slab:
#1988/0 (ThaumicTinkerer:wardSlab)

Pam's blocks: (buggy and mostly useless, but obtainable)
#1414 and #1414/1 through /3 (harvestcraft:sink)
#1564 (harvestcraft:oven)
#1586 (harvestcraft:presser)
#1786 (harvestcraft:cuttingboard)
#1801 (harvestcraft:market)
#1914 (harvestcraft:animaltrap)
#1949 (harvestcraft:churn)
#1974 (harvestcraft:fishtrap)
#2045 (harvestcraft:quern)
#1659 (harvestcraft:pot)

Pam's items: (unobtainable and useless)
#6564 (harvestcraft:fishtrapbaitItem)
#6633 (harvestcraft:fruitbaitItem)
#6662 (harvestcraft:grainbaitItem)
#6681 (harvestcraft:veggiebaitItem)

Also notable is the fact that the waxcomb and honeycomb don't craft into wax and honey anymore, making the food items, candles & hardened leather unobtainable. That said, it may all have been unobtainable from the start since I can't recall how to get a Pam's Queen Bee.

Also also there's a bunch of unobtainable, textureless and/or nameless items in NEI that would be nice to remove but that's probably very low priority. Searching ".name" in NEI should show most of them.
```

**Comment by Xefyr0** [comment]
Hi it's Xefyr here, the one who originally posted this in the Discord.
I made a mistake - Almost all of Pam's machines are functional except:
The Sink, which has a buggy localized name and doesn't properly use the variant textures in-world.
The Market, which crashes the game when interacting with it and is accordingly unobtainable.
Instead, the real issue is that none of the recipes involving Pam's machines show up in JEI - and also that the Baits aren't craftable in the Crafting Table and only three out of the four (fruit, grain and veggie) can be made in the Presser.
The other thing is that wax and honey can be made from combs through the (actually functional) presser, so the whole issue with hardened leather & candles being unobtainable is false and moot.
