### ISSUE TITLE
The Scout's quest tree locked itself after a new player joined my party

### ISSUE THREAD

**Issue by LordGrill** [Midnight145/blightfall-issue-tracker#95]
I have a server set up, running the most recent version (3.1.1 CE as of writing this.) One of my friends joined me and dropped in Epsilon while I dropped in Gamma. By the time he joined, I had already completed some of the scouting quests. Unfortunately, the Scout's tab in the quest book locked itself again when he joined my party. Any idea why this could have happened?

**Comment by tiflu** [comment]
You cannot party in different domes, as some of the starting quests are dome dependent. Please use the discord server or reddit for support.

**Comment by Midnight145** [comment]
For further context, after you drop and complete scout quests and then party up, each person has different exclusive scout quests completed, leading to an "impossible" situation. HQM then gets confused, and just locks the entirety of the scout tree. This can be fixed by just running `/hqm edit` and using the OP quest book to reset the scout quests and both starting the quests from the same dome.

Unfortunately, there's not really much we can do to fix this, at least that I can think of right off.
